#pragma once

#define OASIS_MOUSE_BUTTON_1         0
#define OASIS_MOUSE_BUTTON_2         1
#define OASIS_MOUSE_BUTTON_3         2
#define OASIS_MOUSE_BUTTON_4         3
#define OASIS_MOUSE_BUTTON_5         4
#define OASIS_MOUSE_BUTTON_6         5
#define OASIS_MOUSE_BUTTON_7         6
#define OASIS_MOUSE_BUTTON_8         7
#define OASIS_MOUSE_BUTTON_LAST      OASIS_MOUSE_BUTTON_8
#define OASIS_MOUSE_BUTTON_LEFT      OASIS_MOUSE_BUTTON_1
#define OASIS_MOUSE_BUTTON_RIGHT     OASIS_MOUSE_BUTTON_2
#define OASIS_MOUSE_BUTTON_MIDDLE    OASIS_MOUSE_BUTTON_3